services:
   beasiswa-api:
      container_name: beasiswa-api
      build:
         context: ./
         dockerfile: ./Dockerfile
      ports:
         - 1006:80
      networks:
         - pps-network
      volumes:
         - ./:/var/www/html
      restart: always

networks:
   pps-network:
      external: true
